// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: apply.sql

package db

import (
	"context"
	"time"
)

const bumpFetchFailures = `-- name: BumpFetchFailures :execrows
UPDATE driftless.object_state SET fetch_failures = fetch_failures + 1
WHERE object_type = $1 AND object_id = $2
`

type BumpFetchFailuresParams struct {
	ObjectType string
	ObjectID   string
}

func (q *Queries) BumpFetchFailures(ctx context.Context, arg BumpFetchFailuresParams) (int64, error) {
	result, err := q.db.Exec(ctx, bumpFetchFailures, arg.ObjectType, arg.ObjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEventForApply = `-- name: GetEventForApply :one
SELECT type, payload FROM driftless.events WHERE event_id = $1
`

type GetEventForApplyRow struct {
	Type    string
	Payload []byte
}

func (q *Queries) GetEventForApply(ctx context.Context, eventID string) (GetEventForApplyRow, error) {
	row := q.db.QueryRow(ctx, getEventForApply, eventID)
	var i GetEventForApplyRow
	err := row.Scan(&i.Type, &i.Payload)
	return i, err
}

const getObjectState = `-- name: GetObjectState :one
SELECT object_type, object_id, last_synced_at, last_event_created, last_event_id, sync_source, fetch_failures FROM driftless.object_state WHERE object_type = $1 AND object_id = $2
`

type GetObjectStateParams struct {
	ObjectType string
	ObjectID   string
}

func (q *Queries) GetObjectState(ctx context.Context, arg GetObjectStateParams) (DriftlessObjectState, error) {
	row := q.db.QueryRow(ctx, getObjectState, arg.ObjectType, arg.ObjectID)
	var i DriftlessObjectState
	err := row.Scan(
		&i.ObjectType,
		&i.ObjectID,
		&i.LastSyncedAt,
		&i.LastEventCreated,
		&i.LastEventID,
		&i.SyncSource,
		&i.FetchFailures,
	)
	return i, err
}

const markEventProcessed = `-- name: MarkEventProcessed :exec
UPDATE driftless.events SET processed_at = now()
WHERE event_id = $1 AND processed_at IS NULL
`

func (q *Queries) MarkEventProcessed(ctx context.Context, eventID string) error {
	_, err := q.db.Exec(ctx, markEventProcessed, eventID)
	return err
}

const upsertObjectState = `-- name: UpsertObjectState :exec
INSERT INTO driftless.object_state (object_type, object_id, last_synced_at, last_event_created, last_event_id, sync_source, fetch_failures)
VALUES ($1, $2, now(), $3, $4, $5, 0)
ON CONFLICT (object_type, object_id) DO UPDATE SET
  last_synced_at = now(),
  last_event_created = GREATEST(driftless.object_state.last_event_created, EXCLUDED.last_event_created),
  last_event_id = CASE
    WHEN COALESCE(EXCLUDED.last_event_created, '-infinity'::timestamptz)
         >= COALESCE(driftless.object_state.last_event_created, '-infinity'::timestamptz)
    THEN EXCLUDED.last_event_id
    ELSE driftless.object_state.last_event_id
  END,
  sync_source = EXCLUDED.sync_source,
  fetch_failures = 0
`

type UpsertObjectStateParams struct {
	ObjectType       string
	ObjectID         string
	LastEventCreated *time.Time
	LastEventID      *string
	SyncSource       string
}

// Bookkeeping after a successful apply. last_event_* only move forward so
// a slow concurrent apply can never rewind what a newer one recorded.
func (q *Queries) UpsertObjectState(ctx context.Context, arg UpsertObjectStateParams) error {
	_, err := q.db.Exec(ctx, upsertObjectState,
		arg.ObjectType,
		arg.ObjectID,
		arg.LastEventCreated,
		arg.LastEventID,
		arg.SyncSource,
	)
	return err
}
