// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: backfill.sql

package db

import (
	"context"
	"time"
)

const advanceBackfillCursor = `-- name: AdvanceBackfillCursor :exec
UPDATE driftless.backfill_tasks
SET cursor = $2,
    pages_done = pages_done + 1,
    objects_done = objects_done + $3,
    updated_at = now()
WHERE id = $1
`

type AdvanceBackfillCursorParams struct {
	ID          int64
	Cursor      *string
	ObjectsDone int32
}

// Committed in the same transaction as the page's upserts: crash recovery
// resumes at this page boundary.
func (q *Queries) AdvanceBackfillCursor(ctx context.Context, arg AdvanceBackfillCursorParams) error {
	_, err := q.db.Exec(ctx, advanceBackfillCursor, arg.ID, arg.Cursor, arg.ObjectsDone)
	return err
}

const cancelBackfillRun = `-- name: CancelBackfillRun :execrows
UPDATE driftless.backfill_runs SET status = 'cancelled', finished_at = now()
WHERE id = $1 AND status = 'running'
`

// Records a deliberate stop, so auto_resume leaves the run alone.
func (q *Queries) CancelBackfillRun(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, cancelBackfillRun, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createBackfillRun = `-- name: CreateBackfillRun :one
INSERT INTO driftless.backfill_runs (requested_by, since)
VALUES ($1, $2)
RETURNING id, started_at, finished_at, requested_by, since, status
`

type CreateBackfillRunParams struct {
	RequestedBy string
	Since       *time.Time
}

func (q *Queries) CreateBackfillRun(ctx context.Context, arg CreateBackfillRunParams) (DriftlessBackfillRun, error) {
	row := q.db.QueryRow(ctx, createBackfillRun, arg.RequestedBy, arg.Since)
	var i DriftlessBackfillRun
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.RequestedBy,
		&i.Since,
		&i.Status,
	)
	return i, err
}

const createBackfillTask = `-- name: CreateBackfillTask :one
INSERT INTO driftless.backfill_tasks (run_id, object_type)
VALUES ($1, $2)
ON CONFLICT (run_id, object_type) DO UPDATE SET run_id = EXCLUDED.run_id
RETURNING id, run_id, object_type, status, cursor, pages_done, objects_done, last_error, updated_at
`

type CreateBackfillTaskParams struct {
	RunID      int64
	ObjectType string
}

func (q *Queries) CreateBackfillTask(ctx context.Context, arg CreateBackfillTaskParams) (DriftlessBackfillTask, error) {
	row := q.db.QueryRow(ctx, createBackfillTask, arg.RunID, arg.ObjectType)
	var i DriftlessBackfillTask
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ObjectType,
		&i.Status,
		&i.Cursor,
		&i.PagesDone,
		&i.ObjectsDone,
		&i.LastError,
		&i.UpdatedAt,
	)
	return i, err
}

const finishBackfillRun = `-- name: FinishBackfillRun :exec
UPDATE driftless.backfill_runs SET status = $2, finished_at = now() WHERE id = $1
`

type FinishBackfillRunParams struct {
	ID     int64
	Status string
}

func (q *Queries) FinishBackfillRun(ctx context.Context, arg FinishBackfillRunParams) error {
	_, err := q.db.Exec(ctx, finishBackfillRun, arg.ID, arg.Status)
	return err
}

const finishBackfillTask = `-- name: FinishBackfillTask :exec
UPDATE driftless.backfill_tasks
SET status = $2, last_error = $3, updated_at = now()
WHERE id = $1
`

type FinishBackfillTaskParams struct {
	ID        int64
	Status    string
	LastError *string
}

func (q *Queries) FinishBackfillTask(ctx context.Context, arg FinishBackfillTaskParams) error {
	_, err := q.db.Exec(ctx, finishBackfillTask, arg.ID, arg.Status, arg.LastError)
	return err
}

const getBackfillRun = `-- name: GetBackfillRun :one
SELECT id, started_at, finished_at, requested_by, since, status FROM driftless.backfill_runs WHERE id = $1
`

func (q *Queries) GetBackfillRun(ctx context.Context, id int64) (DriftlessBackfillRun, error) {
	row := q.db.QueryRow(ctx, getBackfillRun, id)
	var i DriftlessBackfillRun
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.RequestedBy,
		&i.Since,
		&i.Status,
	)
	return i, err
}

const listResumableRuns = `-- name: ListResumableRuns :many
SELECT id, started_at, finished_at, requested_by, since, status FROM driftless.backfill_runs WHERE status = 'running' ORDER BY id
`

// Runs a crash left in progress; serve's auto_resume picks these up.
// Cancelled runs are deliberately absent: a human stopped them, so a
// human restarts them.
func (q *Queries) ListResumableRuns(ctx context.Context) ([]DriftlessBackfillRun, error) {
	rows, err := q.db.Query(ctx, listResumableRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DriftlessBackfillRun
	for rows.Next() {
		var i DriftlessBackfillRun
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.RequestedBy,
			&i.Since,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunTasks = `-- name: ListRunTasks :many
SELECT id, run_id, object_type, status, cursor, pages_done, objects_done, last_error, updated_at FROM driftless.backfill_tasks WHERE run_id = $1 ORDER BY id
`

func (q *Queries) ListRunTasks(ctx context.Context, runID int64) ([]DriftlessBackfillTask, error) {
	rows, err := q.db.Query(ctx, listRunTasks, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DriftlessBackfillTask
	for rows.Next() {
		var i DriftlessBackfillTask
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ObjectType,
			&i.Status,
			&i.Cursor,
			&i.PagesDone,
			&i.ObjectsDone,
			&i.LastError,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactivateBackfillRun = `-- name: ReactivateBackfillRun :execrows
UPDATE driftless.backfill_runs SET status = 'running', finished_at = NULL
WHERE id = $1 AND status IN ('running', 'cancelled')
`

// An explicit resume of a cancelled run puts it back in flight.
func (q *Queries) ReactivateBackfillRun(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, reactivateBackfillRun, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const startBackfillTask = `-- name: StartBackfillTask :exec
UPDATE driftless.backfill_tasks SET status = 'running', updated_at = now() WHERE id = $1
`

func (q *Queries) StartBackfillTask(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, startBackfillTask, id)
	return err
}
