// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"
	"time"
)

const countEventsBySource = `-- name: CountEventsBySource :one
SELECT
  count(*) FILTER (WHERE source = 'webhook') AS webhook,
  count(*) FILTER (WHERE source = 'sweep') AS sweep
FROM driftless.events
`

type CountEventsBySourceRow struct {
	Webhook int64
	Sweep   int64
}

func (q *Queries) CountEventsBySource(ctx context.Context) (CountEventsBySourceRow, error) {
	row := q.db.QueryRow(ctx, countEventsBySource)
	var i CountEventsBySourceRow
	err := row.Scan(&i.Webhook, &i.Sweep)
	return i, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT event_id, type, api_version, account_id, created, received_at, source, payload, processed_at, livemode FROM driftless.events WHERE event_id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, eventID string) (DriftlessEvent, error) {
	row := q.db.QueryRow(ctx, getEventByID, eventID)
	var i DriftlessEvent
	err := row.Scan(
		&i.EventID,
		&i.Type,
		&i.ApiVersion,
		&i.AccountID,
		&i.Created,
		&i.ReceivedAt,
		&i.Source,
		&i.Payload,
		&i.ProcessedAt,
		&i.Livemode,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :execrows
INSERT INTO driftless.events (event_id, type, api_version, account_id, created, source, payload, livemode)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (event_id) DO NOTHING
`

type InsertEventParams struct {
	EventID    string
	Type       string
	ApiVersion *string
	AccountID  *string
	Created    time.Time
	Source     string
	Payload    []byte
	Livemode   bool
}

// Append-only event log. A duplicate delivery affects zero rows, which is
// how ingest distinguishes inserted from duplicate.
func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertEvent,
		arg.EventID,
		arg.Type,
		arg.ApiVersion,
		arg.AccountID,
		arg.Created,
		arg.Source,
		arg.Payload,
		arg.Livemode,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeOldEvents = `-- name: PurgeOldEvents :execrows
WITH victims AS (
  SELECT e.event_id FROM driftless.events e
  WHERE e.received_at < $1 AND e.processed_at IS NOT NULL
), purged_gaps AS (
  DELETE FROM driftless.gaps WHERE event_id IN (SELECT event_id FROM victims)
)
DELETE FROM driftless.events WHERE event_id IN (SELECT event_id FROM victims)
`

// Gap audit rows referencing a purged event go with it; an audit trail
// for an event the log no longer holds cannot be inspected anyway.
func (q *Queries) PurgeOldEvents(ctx context.Context, receivedAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeOldEvents, receivedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
