// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"
	"time"
)

const insertEvent = `-- name: InsertEvent :execrows
INSERT INTO driftless.events (event_id, type, api_version, account_id, created, source, payload, livemode)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (event_id) DO NOTHING
`

type InsertEventParams struct {
	EventID    string
	Type       string
	ApiVersion *string
	AccountID  *string
	Created    time.Time
	Source     string
	Payload    []byte
	Livemode   bool
}

// Append-only event log. A duplicate delivery affects zero rows, which is
// how ingest distinguishes inserted from duplicate.
func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertEvent,
		arg.EventID,
		arg.Type,
		arg.ApiVersion,
		arg.AccountID,
		arg.Created,
		arg.Source,
		arg.Payload,
		arg.Livemode,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
