// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package db

import (
	"context"
	"time"
)

const claimJob = `-- name: ClaimJob :one
UPDATE driftless.jobs
SET status = 'running',
    claimed_until = now() + $1::interval,
    attempts = attempts + 1,
    updated_at = now()
WHERE id = (
  SELECT id FROM driftless.jobs
  WHERE status = 'pending' AND run_after <= now()
  ORDER BY priority, id
  LIMIT 1
  FOR UPDATE SKIP LOCKED
)
RETURNING id, kind, object_type, object_id, latest_event_id, latest_event_created, status, priority, attempts, max_attempts, run_after, claimed_until, last_error, created_at, updated_at
`

// Atomic claim: the SKIP LOCKED subquery guarantees no two workers get the
// same row. attempts counts started tries, so jobs that crash a worker are
// bounded by max_attempts through the reaper as well as the failure path.
func (q *Queries) ClaimJob(ctx context.Context, visibilityTimeout time.Duration) (DriftlessJob, error) {
	row := q.db.QueryRow(ctx, claimJob, visibilityTimeout)
	var i DriftlessJob
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ObjectType,
		&i.ObjectID,
		&i.LatestEventID,
		&i.LatestEventCreated,
		&i.Status,
		&i.Priority,
		&i.Attempts,
		&i.MaxAttempts,
		&i.RunAfter,
		&i.ClaimedUntil,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeJob = `-- name: CompleteJob :one
UPDATE driftless.jobs
SET status = CASE
      WHEN COALESCE(latest_event_created, '-infinity'::timestamptz)
           > COALESCE($2::timestamptz, '-infinity'::timestamptz)
        OR (COALESCE(latest_event_created, '-infinity'::timestamptz)
            = COALESCE($2::timestamptz, '-infinity'::timestamptz)
            AND COALESCE(latest_event_id, '') > COALESCE($3::text, ''))
      THEN 'pending'
      ELSE 'done'
    END,
    run_after = now(),
    claimed_until = NULL,
    updated_at = now()
WHERE id = $1 AND status = 'running'
RETURNING status
`

type CompleteJobParams struct {
	ID                  int64
	ClaimedEventCreated *time.Time
	ClaimedEventID      *string
}

// If a newer event was coalesced onto the job while it ran, the work that
// just finished may be stale: requeue instead of done. Newer follows the
// same (created, id) order as the payload-mode guard, ties included.
func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) (string, error) {
	row := q.db.QueryRow(ctx, completeJob, arg.ID, arg.ClaimedEventCreated, arg.ClaimedEventID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const countJobsByStatus = `-- name: CountJobsByStatus :many
SELECT status, count(*) AS count FROM driftless.jobs GROUP BY status
`

type CountJobsByStatusRow struct {
	Status string
	Count  int64
}

func (q *Queries) CountJobsByStatus(ctx context.Context) ([]CountJobsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countJobsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountJobsByStatusRow
	for rows.Next() {
		var i CountJobsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueJob = `-- name: EnqueueJob :one
INSERT INTO driftless.jobs (kind, object_type, object_id, latest_event_id, latest_event_created, priority)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (object_type, object_id) WHERE status IN ('pending','running')
DO UPDATE SET
  latest_event_id = CASE
    WHEN COALESCE(EXCLUDED.latest_event_created, '-infinity') > COALESCE(driftless.jobs.latest_event_created, '-infinity')
      OR (COALESCE(EXCLUDED.latest_event_created, '-infinity') = COALESCE(driftless.jobs.latest_event_created, '-infinity')
          AND COALESCE(EXCLUDED.latest_event_id, '') > COALESCE(driftless.jobs.latest_event_id, ''))
    THEN EXCLUDED.latest_event_id
    ELSE driftless.jobs.latest_event_id
  END,
  latest_event_created = GREATEST(driftless.jobs.latest_event_created, EXCLUDED.latest_event_created),
  updated_at = now()
RETURNING id, (xmax = 0) AS inserted
`

type EnqueueJobParams struct {
	Kind               string
	ObjectType         string
	ObjectID           string
	LatestEventID      *string
	LatestEventCreated *time.Time
	Priority           int16
}

type EnqueueJobRow struct {
	ID       int64
	Inserted bool
}

// Coalescing enqueue: at most one live job per (object_type, object_id).
// A conflict bumps the existing job to the newest event instead of adding a
// row; the bump only moves latest_event_* forward, never backward.
func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (EnqueueJobRow, error) {
	row := q.db.QueryRow(ctx, enqueueJob,
		arg.Kind,
		arg.ObjectType,
		arg.ObjectID,
		arg.LatestEventID,
		arg.LatestEventCreated,
		arg.Priority,
	)
	var i EnqueueJobRow
	err := row.Scan(&i.ID, &i.Inserted)
	return i, err
}

const failJob = `-- name: FailJob :one
UPDATE driftless.jobs
SET status = CASE WHEN attempts >= max_attempts THEN 'dead' ELSE 'pending' END,
    run_after = now() + $2::interval,
    claimed_until = NULL,
    last_error = $3,
    updated_at = now()
WHERE id = $1 AND status = 'running'
RETURNING status
`

type FailJobParams struct {
	ID        int64
	Backoff   time.Duration
	LastError *string
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) (string, error) {
	row := q.db.QueryRow(ctx, failJob, arg.ID, arg.Backoff, arg.LastError)
	var status string
	err := row.Scan(&status)
	return status, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, kind, object_type, object_id, latest_event_id, latest_event_created, status, priority, attempts, max_attempts, run_after, claimed_until, last_error, created_at, updated_at FROM driftless.jobs
WHERE status = $1
ORDER BY id
LIMIT $2
`

type ListJobsParams struct {
	Status   string
	RowLimit int32
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]DriftlessJob, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.Status, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DriftlessJob
	for rows.Next() {
		var i DriftlessJob
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ObjectType,
			&i.ObjectID,
			&i.LatestEventID,
			&i.LatestEventCreated,
			&i.Status,
			&i.Priority,
			&i.Attempts,
			&i.MaxAttempts,
			&i.RunAfter,
			&i.ClaimedUntil,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reapExpiredJobs = `-- name: ReapExpiredJobs :execrows
UPDATE driftless.jobs
SET status = CASE WHEN attempts >= max_attempts THEN 'dead' ELSE 'pending' END,
    claimed_until = NULL,
    last_error = COALESCE(last_error, 'worker crashed or lost its claim'),
    updated_at = now()
WHERE status = 'running' AND claimed_until < now()
`

// Resurrect jobs whose worker died without completing or failing them.
func (q *Queries) ReapExpiredJobs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, reapExpiredJobs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryDeadJobs = `-- name: RetryDeadJobs :execrows
UPDATE driftless.jobs
SET status = 'pending', attempts = 0, run_after = now(), last_error = NULL, updated_at = now()
WHERE status = 'dead'
`

func (q *Queries) RetryDeadJobs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, retryDeadJobs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryJob = `-- name: RetryJob :execrows
UPDATE driftless.jobs
SET status = 'pending', attempts = 0, run_after = now(), last_error = NULL, updated_at = now()
WHERE id = $1 AND status = 'dead'
`

func (q *Queries) RetryJob(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, retryJob, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
