// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meta.sql

package db

import (
	"context"
	"time"
)

const forceMeta = `-- name: ForceMeta :exec
INSERT INTO driftless.meta (stripe_account_id, livemode)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE SET
  stripe_account_id = EXCLUDED.stripe_account_id,
  livemode = EXCLUDED.livemode
`

type ForceMetaParams struct {
	StripeAccountID *string
	Livemode        *bool
}

// Unconditionally overwrites the account record.
func (q *Queries) ForceMeta(ctx context.Context, arg ForceMetaParams) error {
	_, err := q.db.Exec(ctx, forceMeta, arg.StripeAccountID, arg.Livemode)
	return err
}

const getMeta = `-- name: GetMeta :one
SELECT stripe_account_id, livemode, initialized_at FROM driftless.meta
`

type GetMetaRow struct {
	StripeAccountID *string
	Livemode        *bool
	InitializedAt   time.Time
}

func (q *Queries) GetMeta(ctx context.Context) (GetMetaRow, error) {
	row := q.db.QueryRow(ctx, getMeta)
	var i GetMetaRow
	err := row.Scan(&i.StripeAccountID, &i.Livemode, &i.InitializedAt)
	return i, err
}

const initMeta = `-- name: InitMeta :execrows
INSERT INTO driftless.meta (stripe_account_id, livemode)
VALUES ($1, $2)
ON CONFLICT (id) DO NOTHING
`

type InitMetaParams struct {
	StripeAccountID *string
	Livemode        *bool
}

// Inserts the account record only if none exists; the row count reports
// whether this call created it.
func (q *Queries) InitMeta(ctx context.Context, arg InitMetaParams) (int64, error) {
	result, err := q.db.Exec(ctx, initMeta, arg.StripeAccountID, arg.Livemode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
