// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type DriftlessBackfillRun struct {
	ID          int64
	StartedAt   time.Time
	FinishedAt  *time.Time
	RequestedBy string
	Since       *time.Time
	Status      string
}

type DriftlessBackfillTask struct {
	ID          int64
	RunID       int64
	ObjectType  string
	Status      string
	Cursor      *string
	PagesDone   int32
	ObjectsDone int32
	LastError   *string
	UpdatedAt   time.Time
}

type DriftlessEvent struct {
	EventID     string
	Type        string
	ApiVersion  *string
	AccountID   *string
	Created     time.Time
	ReceivedAt  time.Time
	Source      string
	Payload     []byte
	ProcessedAt *time.Time
	Livemode    bool
}

type DriftlessGap struct {
	ID           int64
	EventID      string
	DetectedAt   time.Time
	SweepID      int64
	EventCreated time.Time
	Lag          time.Duration
}

type DriftlessJob struct {
	ID                 int64
	Kind               string
	ObjectType         string
	ObjectID           string
	LatestEventID      *string
	LatestEventCreated *time.Time
	Status             string
	Priority           int16
	Attempts           int32
	MaxAttempts        int32
	RunAfter           time.Time
	ClaimedUntil       *time.Time
	LastError          *string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type DriftlessMetum struct {
	ID              bool
	StripeAccountID *string
	Livemode        *bool
	SchemaVersion   string
	InitializedAt   time.Time
}

type DriftlessObjectState struct {
	ObjectType       string
	ObjectID         string
	LastSyncedAt     time.Time
	LastEventCreated *time.Time
	LastEventID      *string
	SyncSource       string
	FetchFailures    int32
}

type DriftlessSweep struct {
	ID         int64
	StartedAt  time.Time
	FinishedAt *time.Time
	WindowFrom time.Time
	WindowTo   time.Time
	EventsSeen int32
	GapsFound  int32
	Status     string
}

type DriftlessVerification struct {
	ID         int64
	StartedAt  time.Time
	FinishedAt *time.Time
	Mode       string
	ObjectType *string
	Checked    int32
	Drifted    int32
	Repaired   int32
	Report     []byte
}
