// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type DriftlessBackfillRun struct {
	ID          int64
	StartedAt   time.Time
	FinishedAt  *time.Time
	RequestedBy string
	Since       *time.Time
	Status      string
}

type DriftlessBackfillTask struct {
	ID          int64
	RunID       int64
	ObjectType  string
	Status      string
	Cursor      *string
	PagesDone   int32
	ObjectsDone int32
	LastError   *string
	UpdatedAt   time.Time
}

type DriftlessEvent struct {
	EventID     string
	Type        string
	ApiVersion  *string
	AccountID   *string
	Created     time.Time
	ReceivedAt  time.Time
	Source      string
	Payload     []byte
	ProcessedAt *time.Time
	Livemode    bool
}

type DriftlessGap struct {
	ID           int64
	EventID      string
	DetectedAt   time.Time
	SweepID      int64
	EventCreated time.Time
	Lag          time.Duration
}

type DriftlessJob struct {
	ID                 int64
	Kind               string
	ObjectType         string
	ObjectID           string
	LatestEventID      *string
	LatestEventCreated *time.Time
	Status             string
	Priority           int16
	Attempts           int32
	MaxAttempts        int32
	RunAfter           time.Time
	ClaimedUntil       *time.Time
	LastError          *string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type DriftlessMetum struct {
	ID              bool
	StripeAccountID *string
	Livemode        *bool
	SchemaVersion   string
	InitializedAt   time.Time
}

type DriftlessObjectState struct {
	ObjectType       string
	ObjectID         string
	LastSyncedAt     time.Time
	LastEventCreated *time.Time
	LastEventID      *string
	SyncSource       string
	FetchFailures    int32
}

type DriftlessSweep struct {
	ID         int64
	StartedAt  time.Time
	FinishedAt *time.Time
	WindowFrom time.Time
	WindowTo   time.Time
	EventsSeen int32
	GapsFound  int32
	Status     string
}

type DriftlessVerification struct {
	ID         int64
	StartedAt  time.Time
	FinishedAt *time.Time
	Mode       string
	ObjectType *string
	Checked    int32
	Drifted    int32
	Repaired   int32
	Report     []byte
}

type StripeCharge struct {
	ID             string
	Data           []byte
	Customer       *string
	Invoice        *string
	PaymentIntent  *string
	Status         *string
	Amount         *int64
	AmountRefunded *int64
	Currency       *string
	Paid           *bool
	Refunded       *bool
	Created        *time.Time
	Livemode       *bool
	AccountID      *string
	IsDeleted      bool
	DeletedAt      *time.Time
	UpdatedAt      time.Time
}

type StripeCheckoutSession struct {
	ID            string
	Data          []byte
	Customer      *string
	Subscription  *string
	PaymentIntent *string
	Status        *string
	Mode          *string
	AmountTotal   *int64
	Currency      *string
	Created       *time.Time
	Livemode      *bool
	AccountID     *string
	IsDeleted     bool
	DeletedAt     *time.Time
	UpdatedAt     time.Time
}

type StripeCustomer struct {
	ID         string
	Data       []byte
	Email      *string
	Name       *string
	Created    *time.Time
	Currency   *string
	Delinquent *bool
	Livemode   *bool
	AccountID  *string
	IsDeleted  bool
	DeletedAt  *time.Time
	UpdatedAt  time.Time
}

type StripeDispute struct {
	ID            string
	Data          []byte
	Charge        *string
	PaymentIntent *string
	Status        *string
	Amount        *int64
	Currency      *string
	Reason        *string
	EvidenceDueBy *time.Time
	Created       *time.Time
	Livemode      *bool
	AccountID     *string
	IsDeleted     bool
	DeletedAt     *time.Time
	UpdatedAt     time.Time
}

type StripeInvoice struct {
	ID           string
	Data         []byte
	Customer     *string
	Subscription *string
	Status       *string
	Total        *int64
	AmountPaid   *int64
	AmountDue    *int64
	Currency     *string
	PeriodStart  *time.Time
	PeriodEnd    *time.Time
	Number       *string
	Created      *time.Time
	Livemode     *bool
	AccountID    *string
	IsDeleted    bool
	DeletedAt    *time.Time
	UpdatedAt    time.Time
}

type StripePaymentIntent struct {
	ID           string
	Data         []byte
	Customer     *string
	Status       *string
	Amount       *int64
	Currency     *string
	LatestCharge *string
	Created      *time.Time
	Livemode     *bool
	AccountID    *string
	IsDeleted    bool
	DeletedAt    *time.Time
	UpdatedAt    time.Time
}

type StripePaymentMethod struct {
	ID        string
	Data      []byte
	Customer  *string
	Type      *string
	CardBrand *string
	CardLast4 *string
	Created   *time.Time
	Livemode  *bool
	AccountID *string
	IsDeleted bool
	DeletedAt *time.Time
	UpdatedAt time.Time
}

type StripePrice struct {
	ID                string
	Data              []byte
	Product           *string
	Active            *bool
	Currency          *string
	UnitAmount        *int64
	RecurringInterval *string
	Type              *string
	Created           *time.Time
	Livemode          *bool
	AccountID         *string
	IsDeleted         bool
	DeletedAt         *time.Time
	UpdatedAt         time.Time
}

type StripeProduct struct {
	ID        string
	Data      []byte
	Name      *string
	Active    *bool
	Type      *string
	Created   *time.Time
	Livemode  *bool
	AccountID *string
	IsDeleted bool
	DeletedAt *time.Time
	UpdatedAt time.Time
}

type StripeRefund struct {
	ID            string
	Data          []byte
	Charge        *string
	PaymentIntent *string
	Status        *string
	Amount        *int64
	Currency      *string
	Reason        *string
	Created       *time.Time
	Livemode      *bool
	AccountID     *string
	IsDeleted     bool
	DeletedAt     *time.Time
	UpdatedAt     time.Time
}

type StripeSetupIntent struct {
	ID            string
	Data          []byte
	Customer      *string
	Status        *string
	PaymentMethod *string
	Created       *time.Time
	Livemode      *bool
	AccountID     *string
	IsDeleted     bool
	DeletedAt     *time.Time
	UpdatedAt     time.Time
}

type StripeSubscription struct {
	ID                 string
	Data               []byte
	Customer           *string
	Status             *string
	CancelAtPeriodEnd  *bool
	CurrentPeriodStart *time.Time
	CurrentPeriodEnd   *time.Time
	CanceledAt         *time.Time
	TrialEnd           *time.Time
	Created            *time.Time
	Livemode           *bool
	AccountID          *string
	IsDeleted          bool
	DeletedAt          *time.Time
	UpdatedAt          time.Time
}

type StripeSubscriptionItem struct {
	ID           string
	Data         []byte
	Subscription *string
	Price        *string
	Quantity     *int64
	Created      *time.Time
	Livemode     *bool
	AccountID    *string
	IsDeleted    bool
	DeletedAt    *time.Time
	UpdatedAt    time.Time
}
