// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: status.sql

package db

import (
	"context"
	"time"
)

const statusEvents = `-- name: StatusEvents :one
SELECT
  count(*) AS total,
  count(*) FILTER (WHERE processed_at IS NULL) AS unprocessed,
  coalesce(max(received_at), 'epoch')::timestamptz AS last_received
FROM driftless.events
`

type StatusEventsRow struct {
	Total        int64
	Unprocessed  int64
	LastReceived time.Time
}

func (q *Queries) StatusEvents(ctx context.Context) (StatusEventsRow, error) {
	row := q.db.QueryRow(ctx, statusEvents)
	var i StatusEventsRow
	err := row.Scan(&i.Total, &i.Unprocessed, &i.LastReceived)
	return i, err
}

const statusGapsLastDay = `-- name: StatusGapsLastDay :one
SELECT count(*) FROM driftless.gaps
WHERE detected_at > now() - interval '24 hours'
`

func (q *Queries) StatusGapsLastDay(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, statusGapsLastDay)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const statusLastSweep = `-- name: StatusLastSweep :one
SELECT window_from, window_to, finished_at, events_seen, gaps_found
FROM driftless.sweeps
WHERE status = 'done'
ORDER BY id DESC
LIMIT 1
`

type StatusLastSweepRow struct {
	WindowFrom time.Time
	WindowTo   time.Time
	FinishedAt *time.Time
	EventsSeen int32
	GapsFound  int32
}

func (q *Queries) StatusLastSweep(ctx context.Context) (StatusLastSweepRow, error) {
	row := q.db.QueryRow(ctx, statusLastSweep)
	var i StatusLastSweepRow
	err := row.Scan(
		&i.WindowFrom,
		&i.WindowTo,
		&i.FinishedAt,
		&i.EventsSeen,
		&i.GapsFound,
	)
	return i, err
}

const statusLatestBackfillRun = `-- name: StatusLatestBackfillRun :one
SELECT r.id, r.status, r.started_at, r.finished_at,
  (SELECT count(*) FROM driftless.backfill_tasks t WHERE t.run_id = r.id AND t.status = 'done') AS tasks_done,
  (SELECT count(*) FROM driftless.backfill_tasks t WHERE t.run_id = r.id) AS tasks_total,
  (SELECT coalesce(sum(t.objects_done), 0)::bigint FROM driftless.backfill_tasks t WHERE t.run_id = r.id) AS objects_done
FROM driftless.backfill_runs r
ORDER BY r.id DESC
LIMIT 1
`

type StatusLatestBackfillRunRow struct {
	ID          int64
	Status      string
	StartedAt   time.Time
	FinishedAt  *time.Time
	TasksDone   int64
	TasksTotal  int64
	ObjectsDone int64
}

func (q *Queries) StatusLatestBackfillRun(ctx context.Context) (StatusLatestBackfillRunRow, error) {
	row := q.db.QueryRow(ctx, statusLatestBackfillRun)
	var i StatusLatestBackfillRunRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.TasksDone,
		&i.TasksTotal,
		&i.ObjectsDone,
	)
	return i, err
}

const statusLatestVerification = `-- name: StatusLatestVerification :one
SELECT mode, started_at, finished_at, checked, drifted, repaired
FROM driftless.verifications
ORDER BY id DESC
LIMIT 1
`

type StatusLatestVerificationRow struct {
	Mode       string
	StartedAt  time.Time
	FinishedAt *time.Time
	Checked    int32
	Drifted    int32
	Repaired   int32
}

func (q *Queries) StatusLatestVerification(ctx context.Context) (StatusLatestVerificationRow, error) {
	row := q.db.QueryRow(ctx, statusLatestVerification)
	var i StatusLatestVerificationRow
	err := row.Scan(
		&i.Mode,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Checked,
		&i.Drifted,
		&i.Repaired,
	)
	return i, err
}

const statusOldestLiveJob = `-- name: StatusOldestLiveJob :one
SELECT coalesce(min(latest_event_created), 'epoch')::timestamptz AS oldest
FROM driftless.jobs
WHERE status IN ('pending', 'running')
`

func (q *Queries) StatusOldestLiveJob(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, statusOldestLiveJob)
	var oldest time.Time
	err := row.Scan(&oldest)
	return oldest, err
}

const statusUnprocessedEventTypes = `-- name: StatusUnprocessedEventTypes :many
SELECT type, count(*) AS count
FROM driftless.events
WHERE processed_at IS NULL
GROUP BY type
ORDER BY count DESC, type
`

type StatusUnprocessedEventTypesRow struct {
	Type  string
	Count int64
}

func (q *Queries) StatusUnprocessedEventTypes(ctx context.Context) ([]StatusUnprocessedEventTypesRow, error) {
	rows, err := q.db.Query(ctx, statusUnprocessedEventTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatusUnprocessedEventTypesRow
	for rows.Next() {
		var i StatusUnprocessedEventTypesRow
		if err := rows.Scan(&i.Type, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
