// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sweep.sql

package db

import (
	"context"
	"time"
)

const countWebhookEventsBetween = `-- name: CountWebhookEventsBetween :one
SELECT count(*) FROM driftless.events
WHERE source = 'webhook' AND received_at BETWEEN $1 AND $2
`

type CountWebhookEventsBetweenParams struct {
	ReceivedAt   time.Time
	ReceivedAt_2 time.Time
}

// Zero webhook arrivals in a window with gaps found means deliveries are
// not reaching this endpoint at all.
func (q *Queries) CountWebhookEventsBetween(ctx context.Context, arg CountWebhookEventsBetweenParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWebhookEventsBetween, arg.ReceivedAt, arg.ReceivedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSweep = `-- name: CreateSweep :one
INSERT INTO driftless.sweeps (window_from, window_to)
VALUES ($1, $2)
RETURNING id, started_at, finished_at, window_from, window_to, events_seen, gaps_found, status
`

type CreateSweepParams struct {
	WindowFrom time.Time
	WindowTo   time.Time
}

func (q *Queries) CreateSweep(ctx context.Context, arg CreateSweepParams) (DriftlessSweep, error) {
	row := q.db.QueryRow(ctx, createSweep, arg.WindowFrom, arg.WindowTo)
	var i DriftlessSweep
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.WindowFrom,
		&i.WindowTo,
		&i.EventsSeen,
		&i.GapsFound,
		&i.Status,
	)
	return i, err
}

const finishSweep = `-- name: FinishSweep :exec
UPDATE driftless.sweeps
SET status = $2, finished_at = now(), events_seen = $3, gaps_found = $4
WHERE id = $1
`

type FinishSweepParams struct {
	ID         int64
	Status     string
	EventsSeen int32
	GapsFound  int32
}

func (q *Queries) FinishSweep(ctx context.Context, arg FinishSweepParams) error {
	_, err := q.db.Exec(ctx, finishSweep,
		arg.ID,
		arg.Status,
		arg.EventsSeen,
		arg.GapsFound,
	)
	return err
}

const getLastSuccessfulSweep = `-- name: GetLastSuccessfulSweep :one
SELECT id, started_at, finished_at, window_from, window_to, events_seen, gaps_found, status FROM driftless.sweeps WHERE status = 'done' ORDER BY window_to DESC, id DESC LIMIT 1
`

// The checkpoint: the next window starts overlap before this window_to.
func (q *Queries) GetLastSuccessfulSweep(ctx context.Context) (DriftlessSweep, error) {
	row := q.db.QueryRow(ctx, getLastSuccessfulSweep)
	var i DriftlessSweep
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.WindowFrom,
		&i.WindowTo,
		&i.EventsSeen,
		&i.GapsFound,
		&i.Status,
	)
	return i, err
}

const insertGap = `-- name: InsertGap :exec
INSERT INTO driftless.gaps (event_id, sweep_id, event_created, lag)
VALUES ($1, $2, $3, now() - $3::timestamptz)
`

type InsertGapParams struct {
	EventID      string
	SweepID      int64
	EventCreated time.Time
}

func (q *Queries) InsertGap(ctx context.Context, arg InsertGapParams) error {
	_, err := q.db.Exec(ctx, insertGap, arg.EventID, arg.SweepID, arg.EventCreated)
	return err
}
