// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verify.sql

package db

import (
	"context"
)

const createVerification = `-- name: CreateVerification :one
INSERT INTO driftless.verifications (mode, object_type)
VALUES ($1, $2)
RETURNING id
`

type CreateVerificationParams struct {
	Mode       string
	ObjectType *string
}

func (q *Queries) CreateVerification(ctx context.Context, arg CreateVerificationParams) (int64, error) {
	row := q.db.QueryRow(ctx, createVerification, arg.Mode, arg.ObjectType)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const finishVerification = `-- name: FinishVerification :exec
UPDATE driftless.verifications
SET finished_at = now(), checked = $2, drifted = $3, repaired = $4, report = $5
WHERE id = $1
`

type FinishVerificationParams struct {
	ID       int64
	Checked  int32
	Drifted  int32
	Repaired int32
	Report   []byte
}

func (q *Queries) FinishVerification(ctx context.Context, arg FinishVerificationParams) error {
	_, err := q.db.Exec(ctx, finishVerification,
		arg.ID,
		arg.Checked,
		arg.Drifted,
		arg.Repaired,
		arg.Report,
	)
	return err
}
